/*
 * Decompiled with CFR 0.2.2 (FabricMC 7c48b8c4).
 * 
 * Could not load the following classes:
 *  net.fabricmc.api.EnvType
 *  net.fabricmc.api.Environment
 */
package net.minecraft.client.render.entity.model;

import com.google.common.collect.ImmutableMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.block.WoodType;
import net.minecraft.client.model.Dilation;
import net.minecraft.client.model.TexturedModelData;
import net.minecraft.client.render.block.entity.BedBlockEntityRenderer;
import net.minecraft.client.render.block.entity.ConduitBlockEntityRenderer;
import net.minecraft.client.render.block.entity.DecoratedPotBlockEntityRenderer;
import net.minecraft.client.render.block.entity.HangingSignBlockEntityRenderer;
import net.minecraft.client.render.block.entity.SignBlockEntityRenderer;
import net.minecraft.client.render.block.entity.model.BannerBlockModel;
import net.minecraft.client.render.block.entity.model.BannerFlagBlockModel;
import net.minecraft.client.render.block.entity.model.BellBlockModel;
import net.minecraft.client.render.block.entity.model.ChestBlockModel;
import net.minecraft.client.render.entity.DragonEntityModel;
import net.minecraft.client.render.entity.WitherSkullEntityRenderer;
import net.minecraft.client.render.entity.model.AbstractHorseEntityModel;
import net.minecraft.client.render.entity.model.AllayEntityModel;
import net.minecraft.client.render.entity.model.ArmadilloEntityModel;
import net.minecraft.client.render.entity.model.ArmorEntityModel;
import net.minecraft.client.render.entity.model.ArmorStandArmorEntityModel;
import net.minecraft.client.render.entity.model.ArmorStandEntityModel;
import net.minecraft.client.render.entity.model.ArrowEntityModel;
import net.minecraft.client.render.entity.model.AxolotlEntityModel;
import net.minecraft.client.render.entity.model.BatEntityModel;
import net.minecraft.client.render.entity.model.BeeEntityModel;
import net.minecraft.client.render.entity.model.BipedEntityModel;
import net.minecraft.client.render.entity.model.BlazeEntityModel;
import net.minecraft.client.render.entity.model.BoatEntityModel;
import net.minecraft.client.render.entity.model.BoggedEntityModel;
import net.minecraft.client.render.entity.model.BookModel;
import net.minecraft.client.render.entity.model.BreezeEntityModel;
import net.minecraft.client.render.entity.model.CamelEntityModel;
import net.minecraft.client.render.entity.model.CatEntityModel;
import net.minecraft.client.render.entity.model.ChickenEntityModel;
import net.minecraft.client.render.entity.model.CodEntityModel;
import net.minecraft.client.render.entity.model.CowEntityModel;
import net.minecraft.client.render.entity.model.CreakingEntityModel;
import net.minecraft.client.render.entity.model.CreeperEntityModel;
import net.minecraft.client.render.entity.model.Deadmau5EarsEntityModel;
import net.minecraft.client.render.entity.model.DolphinEntityModel;
import net.minecraft.client.render.entity.model.DonkeyEntityModel;
import net.minecraft.client.render.entity.model.DragonHeadEntityModel;
import net.minecraft.client.render.entity.model.DrownedEntityModel;
import net.minecraft.client.render.entity.model.ElytraEntityModel;
import net.minecraft.client.render.entity.model.EndCrystalEntityModel;
import net.minecraft.client.render.entity.model.EndermanEntityModel;
import net.minecraft.client.render.entity.model.EndermiteEntityModel;
import net.minecraft.client.render.entity.model.EntityModelLayer;
import net.minecraft.client.render.entity.model.EntityModelLayers;
import net.minecraft.client.render.entity.model.EvokerFangsEntityModel;
import net.minecraft.client.render.entity.model.FelineEntityModel;
import net.minecraft.client.render.entity.model.FoxEntityModel;
import net.minecraft.client.render.entity.model.FrogEntityModel;
import net.minecraft.client.render.entity.model.GhastEntityModel;
import net.minecraft.client.render.entity.model.GoatEntityModel;
import net.minecraft.client.render.entity.model.GuardianEntityModel;
import net.minecraft.client.render.entity.model.HoglinEntityModel;
import net.minecraft.client.render.entity.model.IllagerEntityModel;
import net.minecraft.client.render.entity.model.IronGolemEntityModel;
import net.minecraft.client.render.entity.model.LargePufferfishEntityModel;
import net.minecraft.client.render.entity.model.LargeTropicalFishEntityModel;
import net.minecraft.client.render.entity.model.LeashKnotEntityModel;
import net.minecraft.client.render.entity.model.LlamaEntityModel;
import net.minecraft.client.render.entity.model.LlamaSpitEntityModel;
import net.minecraft.client.render.entity.model.MagmaCubeEntityModel;
import net.minecraft.client.render.entity.model.MediumPufferfishEntityModel;
import net.minecraft.client.render.entity.model.MinecartEntityModel;
import net.minecraft.client.render.entity.model.ModelTransformer;
import net.minecraft.client.render.entity.model.PandaEntityModel;
import net.minecraft.client.render.entity.model.ParrotEntityModel;
import net.minecraft.client.render.entity.model.PhantomEntityModel;
import net.minecraft.client.render.entity.model.PigEntityModel;
import net.minecraft.client.render.entity.model.PiglinEntityModel;
import net.minecraft.client.render.entity.model.PiglinHeadEntityModel;
import net.minecraft.client.render.entity.model.PlayerCapeModel;
import net.minecraft.client.render.entity.model.PlayerEntityModel;
import net.minecraft.client.render.entity.model.PolarBearEntityModel;
import net.minecraft.client.render.entity.model.RabbitEntityModel;
import net.minecraft.client.render.entity.model.RaftEntityModel;
import net.minecraft.client.render.entity.model.RavagerEntityModel;
import net.minecraft.client.render.entity.model.SalmonEntityModel;
import net.minecraft.client.render.entity.model.SheepEntityModel;
import net.minecraft.client.render.entity.model.SheepWoolEntityModel;
import net.minecraft.client.render.entity.model.ShieldEntityModel;
import net.minecraft.client.render.entity.model.ShulkerBulletEntityModel;
import net.minecraft.client.render.entity.model.ShulkerEntityModel;
import net.minecraft.client.render.entity.model.SilverfishEntityModel;
import net.minecraft.client.render.entity.model.SkeletonEntityModel;
import net.minecraft.client.render.entity.model.SkullEntityModel;
import net.minecraft.client.render.entity.model.SlimeEntityModel;
import net.minecraft.client.render.entity.model.SmallPufferfishEntityModel;
import net.minecraft.client.render.entity.model.SmallTropicalFishEntityModel;
import net.minecraft.client.render.entity.model.SnifferEntityModel;
import net.minecraft.client.render.entity.model.SnowGolemEntityModel;
import net.minecraft.client.render.entity.model.SpiderEntityModel;
import net.minecraft.client.render.entity.model.SquidEntityModel;
import net.minecraft.client.render.entity.model.StingerModel;
import net.minecraft.client.render.entity.model.StriderEntityModel;
import net.minecraft.client.render.entity.model.TadpoleEntityModel;
import net.minecraft.client.render.entity.model.TridentEntityModel;
import net.minecraft.client.render.entity.model.TridentRiptideEntityModel;
import net.minecraft.client.render.entity.model.TurtleEntityModel;
import net.minecraft.client.render.entity.model.VexEntityModel;
import net.minecraft.client.render.entity.model.VillagerResemblingModel;
import net.minecraft.client.render.entity.model.WardenEntityModel;
import net.minecraft.client.render.entity.model.WindChargeEntityModel;
import net.minecraft.client.render.entity.model.WitchEntityModel;
import net.minecraft.client.render.entity.model.WitherEntityModel;
import net.minecraft.client.render.entity.model.WolfEntityModel;
import net.minecraft.client.render.entity.model.ZombieVillagerEntityModel;

@Environment(value=EnvType.CLIENT)
public class EntityModels {
    private static final Dilation FISH_PATTERN_DILATION = new Dilation(0.008f);
    private static final Dilation ARMOR_DILATION = new Dilation(1.0f);
    private static final Dilation HAT_DILATION = new Dilation(0.5f);

    public static Map<EntityModelLayer, TexturedModelData> getModels() {
        ImmutableMap.Builder<EntityModelLayer, TexturedModelData> builder = ImmutableMap.builder();
        TexturedModelData lv = TexturedModelData.of(BipedEntityModel.getModelData(Dilation.NONE, 0.0f), 64, 64);
        TexturedModelData lv2 = TexturedModelData.of(ArmorEntityModel.getModelData(ARMOR_DILATION), 64, 32);
        TexturedModelData lv3 = TexturedModelData.of(ArmorEntityModel.getModelData(new Dilation(1.02f)), 64, 32);
        TexturedModelData lv4 = TexturedModelData.of(ArmorEntityModel.getModelData(HAT_DILATION), 64, 32);
        TexturedModelData lv5 = MinecartEntityModel.getTexturedModelData();
        TexturedModelData lv6 = SkullEntityModel.getSkullTexturedModelData();
        TexturedModelData lv7 = TexturedModelData.of(AbstractHorseEntityModel.getModelData(Dilation.NONE), 64, 64);
        TexturedModelData lv8 = TexturedModelData.of(AbstractHorseEntityModel.getBabyHorseModelData(Dilation.NONE), 64, 64);
        ModelTransformer lv9 = ModelTransformer.scaling(0.9375f);
        TexturedModelData lv10 = IllagerEntityModel.getTexturedModelData().transform(lv9);
        TexturedModelData lv11 = AxolotlEntityModel.getTexturedModelData();
        TexturedModelData lv12 = BeeEntityModel.getTexturedModelData();
        TexturedModelData lv13 = CowEntityModel.getTexturedModelData();
        TexturedModelData lv14 = lv13.transform(CowEntityModel.BABY_TRANSFORMER);
        TexturedModelData lv15 = ElytraEntityModel.getTexturedModelData();
        TexturedModelData lv16 = TexturedModelData.of(FelineEntityModel.getModelData(Dilation.NONE), 64, 32);
        TexturedModelData lv17 = lv16.transform(FelineEntityModel.BABY_TRANSFORMER);
        TexturedModelData lv18 = TexturedModelData.of(FelineEntityModel.getModelData(new Dilation(0.01f)), 64, 32);
        TexturedModelData lv19 = TexturedModelData.of(PiglinEntityModel.getModelData(Dilation.NONE), 64, 64);
        TexturedModelData lv20 = TexturedModelData.of(PiglinHeadEntityModel.getModelData(), 64, 64);
        TexturedModelData lv21 = SkullEntityModel.getHeadTexturedModelData();
        TexturedModelData lv22 = LlamaEntityModel.getTexturedModelData(Dilation.NONE);
        TexturedModelData lv23 = LlamaEntityModel.getTexturedModelData(new Dilation(0.5f));
        TexturedModelData lv24 = StriderEntityModel.getTexturedModelData();
        TexturedModelData lv25 = HoglinEntityModel.getTexturedModelData();
        TexturedModelData lv26 = HoglinEntityModel.getBabyTexturedModelData();
        TexturedModelData lv27 = SkeletonEntityModel.getTexturedModelData();
        TexturedModelData lv28 = TexturedModelData.of(VillagerResemblingModel.getModelData(), 64, 64).transform(lv9);
        TexturedModelData lv29 = SpiderEntityModel.getTexturedModelData();
        TexturedModelData lv30 = ArmadilloEntityModel.getTexturedModelData();
        TexturedModelData lv31 = CamelEntityModel.getTexturedModelData();
        TexturedModelData lv32 = ChickenEntityModel.getTexturedModelData();
        TexturedModelData lv33 = GoatEntityModel.getTexturedModelData();
        TexturedModelData lv34 = PandaEntityModel.getTexturedModelData();
        TexturedModelData lv35 = PigEntityModel.getTexturedModelData(Dilation.NONE);
        TexturedModelData lv36 = PigEntityModel.getTexturedModelData(new Dilation(0.5f));
        TexturedModelData lv37 = PolarBearEntityModel.getTexturedModelData();
        TexturedModelData lv38 = SheepEntityModel.getTexturedModelData();
        TexturedModelData lv39 = SheepWoolEntityModel.getTexturedModelData();
        TexturedModelData lv40 = SnifferEntityModel.getTexturedModelData();
        TexturedModelData lv41 = TurtleEntityModel.getTexturedModelData();
        TexturedModelData lv42 = TexturedModelData.of(WolfEntityModel.getTexturedModelData(Dilation.NONE), 64, 32);
        TexturedModelData lv43 = TexturedModelData.of(WolfEntityModel.getTexturedModelData(new Dilation(0.2f)), 64, 32);
        TexturedModelData lv44 = ZombieVillagerEntityModel.getTexturedModelData();
        TexturedModelData lv45 = ArmorStandEntityModel.getTexturedModelData();
        TexturedModelData lv46 = ArmorStandArmorEntityModel.getTexturedModelData(HAT_DILATION);
        TexturedModelData lv47 = ArmorStandArmorEntityModel.getTexturedModelData(ARMOR_DILATION);
        TexturedModelData lv48 = DrownedEntityModel.getTexturedModelData(Dilation.NONE);
        TexturedModelData lv49 = DrownedEntityModel.getTexturedModelData(new Dilation(0.25f));
        TexturedModelData lv50 = SquidEntityModel.getTexturedModelData();
        TexturedModelData lv51 = DolphinEntityModel.getTexturedModelData();
        TexturedModelData lv52 = SalmonEntityModel.getTexturedModelData();
        builder.put(EntityModelLayers.ALLAY, AllayEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.ARMADILLO, lv30);
        builder.put(EntityModelLayers.ARMADILLO_BABY, lv30.transform(ArmadilloEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.ARMOR_STAND, lv45);
        builder.put(EntityModelLayers.ARMOR_STAND_INNER_ARMOR, lv46);
        builder.put(EntityModelLayers.ARMOR_STAND_OUTER_ARMOR, lv47);
        builder.put(EntityModelLayers.ARMOR_STAND_SMALL, lv45.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.ARMOR_STAND_SMALL_INNER_ARMOR, lv46.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.ARMOR_STAND_SMALL_OUTER_ARMOR, lv47.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.ARROW, ArrowEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.AXOLOTL, lv11);
        builder.put(EntityModelLayers.AXOLOTL_BABY, lv11.transform(AxolotlEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.STANDING_BANNER, BannerBlockModel.getTexturedModelData(true));
        builder.put(EntityModelLayers.WALL_BANNER, BannerBlockModel.getTexturedModelData(false));
        builder.put(EntityModelLayers.STANDING_BANNER_FLAG, BannerFlagBlockModel.getTexturedModelData(true));
        builder.put(EntityModelLayers.WALL_BANNER_FLAG, BannerFlagBlockModel.getTexturedModelData(false));
        builder.put(EntityModelLayers.BAT, BatEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.BED_FOOT, BedBlockEntityRenderer.getFootTexturedModelData());
        builder.put(EntityModelLayers.BED_HEAD, BedBlockEntityRenderer.getHeadTexturedModelData());
        builder.put(EntityModelLayers.BEE, lv12);
        builder.put(EntityModelLayers.BEE_BABY, lv12.transform(BeeEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.BEE_STINGER, StingerModel.getTexturedModelData());
        builder.put(EntityModelLayers.BELL, BellBlockModel.getTexturedModelData());
        builder.put(EntityModelLayers.BLAZE, BlazeEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.BOAT, BoatEntityModel.getBaseTexturedModelData());
        builder.put(EntityModelLayers.BOGGED, BoggedEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.BOGGED_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.BOGGED_OUTER_ARMOR, lv2);
        builder.put(EntityModelLayers.BOGGED_OUTER, TexturedModelData.of(BipedEntityModel.getModelData(new Dilation(0.2f), 0.0f), 64, 32));
        builder.put(EntityModelLayers.BOOK, BookModel.getTexturedModelData());
        builder.put(EntityModelLayers.BREEZE, BreezeEntityModel.getTexturedModelData(32, 32));
        builder.put(EntityModelLayers.BREEZE_WIND, BreezeEntityModel.getTexturedModelData(128, 128));
        builder.put(EntityModelLayers.CAT, lv16.transform(CatEntityModel.CAT_TRANSFORMER));
        builder.put(EntityModelLayers.CAT_BABY, lv17.transform(CatEntityModel.CAT_TRANSFORMER));
        builder.put(EntityModelLayers.CAT_COLLAR, lv18.transform(CatEntityModel.CAT_TRANSFORMER));
        builder.put(EntityModelLayers.CAT_BABY_COLLAR, lv18.transform(FelineEntityModel.BABY_TRANSFORMER).transform(CatEntityModel.CAT_TRANSFORMER));
        builder.put(EntityModelLayers.CAMEL, lv31);
        builder.put(EntityModelLayers.CAMEL_BABY, lv31.transform(CamelEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.CAVE_SPIDER, lv29.transform(ModelTransformer.scaling(0.7f)));
        builder.put(EntityModelLayers.CHEST, ChestBlockModel.getSingleTexturedModelData());
        builder.put(EntityModelLayers.CHEST_MINECART, lv5);
        builder.put(EntityModelLayers.CHICKEN, lv32);
        builder.put(EntityModelLayers.CHICKEN_BABY, lv32.transform(ChickenEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.COD, CodEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.COMMAND_BLOCK_MINECART, lv5);
        builder.put(EntityModelLayers.CONDUIT_EYE, ConduitBlockEntityRenderer.getEyeTexturedModelData());
        builder.put(EntityModelLayers.CONDUIT_WIND, ConduitBlockEntityRenderer.getWindTexturedModelData());
        builder.put(EntityModelLayers.CONDUIT_SHELL, ConduitBlockEntityRenderer.getShellTexturedModelData());
        builder.put(EntityModelLayers.CONDUIT, ConduitBlockEntityRenderer.getPlainTexturedModelData());
        builder.put(EntityModelLayers.COW, lv13);
        builder.put(EntityModelLayers.COW_BABY, lv14);
        builder.put(EntityModelLayers.CREAKING, CreakingEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.CREEPER, CreeperEntityModel.getTexturedModelData(Dilation.NONE));
        builder.put(EntityModelLayers.CREEPER_ARMOR, CreeperEntityModel.getTexturedModelData(new Dilation(2.0f)));
        builder.put(EntityModelLayers.CREEPER_HEAD, lv6);
        builder.put(EntityModelLayers.DECORATED_POT_BASE, DecoratedPotBlockEntityRenderer.getTopBottomNeckTexturedModelData());
        builder.put(EntityModelLayers.DECORATED_POT_SIDES, DecoratedPotBlockEntityRenderer.getSidesTexturedModelData());
        builder.put(EntityModelLayers.DOLPHIN, lv51);
        builder.put(EntityModelLayers.DOLPHIN_BABY, lv51.transform(DolphinEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.DONKEY, DonkeyEntityModel.getTexturedModelData(0.87f));
        builder.put(EntityModelLayers.DONKEY_BABY, DonkeyEntityModel.getBabyTexturedModelData(0.87f));
        builder.put(EntityModelLayers.DOUBLE_CHEST_LEFT, ChestBlockModel.getDoubleChestLeftTexturedBlockData());
        builder.put(EntityModelLayers.DOUBLE_CHEST_RIGHT, ChestBlockModel.getDoubleChestRightTexturedBlockData());
        builder.put(EntityModelLayers.DRAGON_SKULL, DragonHeadEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.DROWNED, lv48);
        builder.put(EntityModelLayers.DROWNED_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.DROWNED_OUTER_ARMOR, lv4);
        builder.put(EntityModelLayers.DROWNED_OUTER, lv49);
        builder.put(EntityModelLayers.DROWNED_BABY, lv48.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.DROWNED_BABY_INNER_ARMOR, lv4.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.DROWNED_BABY_OUTER_ARMOR, lv4.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.DROWNED_BABY_OUTER, lv49.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.ELDER_GUARDIAN, GuardianEntityModel.getElderTexturedModelData());
        builder.put(EntityModelLayers.ELYTRA, lv15);
        builder.put(EntityModelLayers.ELYTRA_BABY, lv15.transform(ElytraEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.ENDERMAN, EndermanEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.ENDERMITE, EndermiteEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.ENDER_DRAGON, DragonEntityModel.createTexturedModelData());
        builder.put(EntityModelLayers.END_CRYSTAL, EndCrystalEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.EVOKER, lv10);
        builder.put(EntityModelLayers.EVOKER_FANGS, EvokerFangsEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.FOX, FoxEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.FOX_BABY, FoxEntityModel.getTexturedModelData().transform(FoxEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.FROG, FrogEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.FURNACE_MINECART, lv5);
        builder.put(EntityModelLayers.GHAST, GhastEntityModel.getTexturedModelData());
        ModelTransformer lv53 = ModelTransformer.scaling(6.0f);
        builder.put(EntityModelLayers.GIANT, lv.transform(lv53));
        builder.put(EntityModelLayers.GIANT_INNER_ARMOR, lv4.transform(lv53));
        builder.put(EntityModelLayers.GIANT_OUTER_ARMOR, lv2.transform(lv53));
        builder.put(EntityModelLayers.GLOW_SQUID, lv50);
        builder.put(EntityModelLayers.GLOW_SQUID_BABY, lv50.transform(SquidEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.GOAT, lv33);
        builder.put(EntityModelLayers.GOAT_BABY, lv33.transform(GoatEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.GUARDIAN, GuardianEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.HOGLIN, lv25);
        builder.put(EntityModelLayers.HOGLIN_BABY, lv26);
        builder.put(EntityModelLayers.HOPPER_MINECART, lv5);
        ModelTransformer lv54 = ModelTransformer.scaling(1.1f);
        builder.put(EntityModelLayers.HORSE, lv7.transform(lv54));
        builder.put(EntityModelLayers.HORSE_BABY, lv8.transform(lv54));
        builder.put(EntityModelLayers.HORSE_ARMOR, TexturedModelData.of(AbstractHorseEntityModel.getModelData(new Dilation(0.1f)), 64, 64).transform(lv54));
        builder.put(EntityModelLayers.HORSE_ARMOR_BABY, TexturedModelData.of(AbstractHorseEntityModel.getBabyHorseModelData(new Dilation(0.1f)), 64, 64).transform(lv54));
        ModelTransformer lv55 = ModelTransformer.scaling(1.0625f);
        builder.put(EntityModelLayers.HUSK, lv.transform(lv55));
        builder.put(EntityModelLayers.HUSK_INNER_ARMOR, lv4.transform(lv55));
        builder.put(EntityModelLayers.HUSK_OUTER_ARMOR, lv2.transform(lv55));
        builder.put(EntityModelLayers.HUSK_BABY, lv.transform(BipedEntityModel.BABY_TRANSFORMER).transform(lv55));
        builder.put(EntityModelLayers.HUSK_BABY_INNER_ARMOR, lv4.transform(BipedEntityModel.BABY_TRANSFORMER).transform(lv55));
        builder.put(EntityModelLayers.HUSK_BABY_OUTER_ARMOR, lv2.transform(BipedEntityModel.BABY_TRANSFORMER).transform(lv55));
        builder.put(EntityModelLayers.ILLUSIONER, lv10);
        builder.put(EntityModelLayers.IRON_GOLEM, IronGolemEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.LEASH_KNOT, LeashKnotEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.LLAMA, lv22);
        builder.put(EntityModelLayers.LLAMA_BABY, lv22.transform(LlamaEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.LLAMA_DECOR, lv23);
        builder.put(EntityModelLayers.LLAMA_BABY_DECOR, lv23.transform(LlamaEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.LLAMA_SPIT, LlamaSpitEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.MAGMA_CUBE, MagmaCubeEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.MINECART, lv5);
        builder.put(EntityModelLayers.MOOSHROOM, lv13);
        builder.put(EntityModelLayers.MOOSHROOM_BABY, lv14);
        builder.put(EntityModelLayers.MULE, DonkeyEntityModel.getTexturedModelData(0.92f));
        builder.put(EntityModelLayers.MULE_BABY, DonkeyEntityModel.getBabyTexturedModelData(0.92f));
        builder.put(EntityModelLayers.OCELOT, lv16);
        builder.put(EntityModelLayers.OCELOT_BABY, lv17);
        builder.put(EntityModelLayers.PANDA, lv34);
        builder.put(EntityModelLayers.PANDA_BABY, lv34.transform(PandaEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.PARROT, ParrotEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.PHANTOM, PhantomEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.PIG, lv35);
        builder.put(EntityModelLayers.PIG_BABY, lv35.transform(PigEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.PIG_SADDLE, lv36);
        builder.put(EntityModelLayers.PIG_BABY_SADDLE, lv36.transform(PigEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.PIGLIN, lv19);
        builder.put(EntityModelLayers.PIGLIN_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.PIGLIN_OUTER_ARMOR, lv3);
        builder.put(EntityModelLayers.PIGLIN_BRUTE, lv19);
        builder.put(EntityModelLayers.PIGLIN_BRUTE_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.PIGLIN_BRUTE_OUTER_ARMOR, lv3);
        builder.put(EntityModelLayers.PIGLIN_BABY, lv19.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.PIGLIN_BABY_INNER_ARMOR, lv4.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.PIGLIN_BABY_OUTER_ARMOR, lv3.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.PIGLIN_HEAD, lv20);
        builder.put(EntityModelLayers.PILLAGER, lv10);
        builder.put(EntityModelLayers.PLAYER, TexturedModelData.of(PlayerEntityModel.getTexturedModelData(Dilation.NONE, false), 64, 64));
        builder.put(EntityModelLayers.PLAYER_EARS, Deadmau5EarsEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.PLAYER_CAPE, PlayerCapeModel.getTexturedModelData());
        builder.put(EntityModelLayers.PLAYER_HEAD, lv21);
        builder.put(EntityModelLayers.PLAYER_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.PLAYER_OUTER_ARMOR, lv2);
        builder.put(EntityModelLayers.PLAYER_SLIM, TexturedModelData.of(PlayerEntityModel.getTexturedModelData(Dilation.NONE, true), 64, 64));
        builder.put(EntityModelLayers.PLAYER_SLIM_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.PLAYER_SLIM_OUTER_ARMOR, lv2);
        builder.put(EntityModelLayers.SPIN_ATTACK, TridentRiptideEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.POLAR_BEAR, lv37);
        builder.put(EntityModelLayers.POLAR_BEAR_BABY, lv37.transform(PolarBearEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.PUFFERFISH_BIG, LargePufferfishEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.PUFFERFISH_MEDIUM, MediumPufferfishEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.PUFFERFISH_SMALL, SmallPufferfishEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.RABBIT, RabbitEntityModel.getTexturedModelData(false));
        builder.put(EntityModelLayers.RABBIT_BABY, RabbitEntityModel.getTexturedModelData(true));
        builder.put(EntityModelLayers.RAVAGER, RavagerEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.SALMON, lv52);
        builder.put(EntityModelLayers.SALMON_SMALL, lv52.transform(SalmonEntityModel.SMALL_TRANSFORMER));
        builder.put(EntityModelLayers.SALMON_LARGE, lv52.transform(SalmonEntityModel.LARGE_TRANSFORMER));
        builder.put(EntityModelLayers.SHEEP, lv38);
        builder.put(EntityModelLayers.SHEEP_BABY, lv38.transform(SheepEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.SHEEP_WOOL, lv39);
        builder.put(EntityModelLayers.SHEEP_BABY_WOOL, lv39.transform(SheepEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.SHIELD, ShieldEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.SHULKER, ShulkerEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.SHULKER_BOX, ShulkerEntityModel.getShulkerBoxTexturedModelData());
        builder.put(EntityModelLayers.SHULKER_BULLET, ShulkerBulletEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.SILVERFISH, SilverfishEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.SKELETON, lv27);
        builder.put(EntityModelLayers.SKELETON_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.SKELETON_OUTER_ARMOR, lv2);
        builder.put(EntityModelLayers.SKELETON_HORSE, lv7);
        builder.put(EntityModelLayers.SKELETON_HORSE_BABY, lv8);
        builder.put(EntityModelLayers.SKELETON_SKULL, lv6);
        builder.put(EntityModelLayers.SLIME, SlimeEntityModel.getInnerTexturedModelData());
        builder.put(EntityModelLayers.SLIME_OUTER, SlimeEntityModel.getOuterTexturedModelData());
        builder.put(EntityModelLayers.SNIFFER, lv40);
        builder.put(EntityModelLayers.SNIFFER_BABY, lv40.transform(SnifferEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.SNOW_GOLEM, SnowGolemEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.SPAWNER_MINECART, lv5);
        builder.put(EntityModelLayers.SPIDER, lv29);
        builder.put(EntityModelLayers.SQUID, lv50);
        builder.put(EntityModelLayers.SQUID_BABY, lv50.transform(SquidEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.STRAY, lv27);
        builder.put(EntityModelLayers.STRAY_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.STRAY_OUTER_ARMOR, lv2);
        builder.put(EntityModelLayers.STRAY_OUTER, TexturedModelData.of(BipedEntityModel.getModelData(new Dilation(0.25f), 0.0f), 64, 32));
        builder.put(EntityModelLayers.STRIDER, lv24);
        builder.put(EntityModelLayers.STRIDER_SADDLE, lv24);
        builder.put(EntityModelLayers.STRIDER_BABY, lv24.transform(StriderEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.STRIDER_BABY_SADDLE, lv24.transform(StriderEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.TADPOLE, TadpoleEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.TNT_MINECART, lv5);
        builder.put(EntityModelLayers.TRADER_LLAMA, lv22);
        builder.put(EntityModelLayers.TRADER_LLAMA_BABY, lv22.transform(LlamaEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.TRIDENT, TridentEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.TROPICAL_FISH_LARGE, LargeTropicalFishEntityModel.getTexturedModelData(Dilation.NONE));
        builder.put(EntityModelLayers.TROPICAL_FISH_LARGE_PATTERN, LargeTropicalFishEntityModel.getTexturedModelData(FISH_PATTERN_DILATION));
        builder.put(EntityModelLayers.TROPICAL_FISH_SMALL, SmallTropicalFishEntityModel.getTexturedModelData(Dilation.NONE));
        builder.put(EntityModelLayers.TROPICAL_FISH_SMALL_PATTERN, SmallTropicalFishEntityModel.getTexturedModelData(FISH_PATTERN_DILATION));
        builder.put(EntityModelLayers.TURTLE, lv41);
        builder.put(EntityModelLayers.TURTLE_BABY, lv41.transform(TurtleEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.VEX, VexEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.VILLAGER, lv28);
        builder.put(EntityModelLayers.VILLAGER_BABY, lv28.transform(VillagerResemblingModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.VINDICATOR, lv10);
        builder.put(EntityModelLayers.WARDEN, WardenEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.WANDERING_TRADER, lv28);
        builder.put(EntityModelLayers.WIND_CHARGE, WindChargeEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.WITCH, WitchEntityModel.getTexturedModelData().transform(lv9));
        builder.put(EntityModelLayers.WITHER, WitherEntityModel.getTexturedModelData(Dilation.NONE));
        builder.put(EntityModelLayers.WITHER_ARMOR, WitherEntityModel.getTexturedModelData(HAT_DILATION));
        builder.put(EntityModelLayers.WITHER_SKULL, WitherSkullEntityRenderer.getTexturedModelData());
        ModelTransformer lv56 = ModelTransformer.scaling(1.2f);
        builder.put(EntityModelLayers.WITHER_SKELETON, lv27.transform(lv56));
        builder.put(EntityModelLayers.WITHER_SKELETON_INNER_ARMOR, lv4.transform(lv56));
        builder.put(EntityModelLayers.WITHER_SKELETON_OUTER_ARMOR, lv2.transform(lv56));
        builder.put(EntityModelLayers.WITHER_SKELETON_SKULL, lv6);
        builder.put(EntityModelLayers.WOLF, lv42);
        builder.put(EntityModelLayers.WOLF_ARMOR, lv43);
        builder.put(EntityModelLayers.WOLF_BABY, lv42.transform(WolfEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.WOLF_BABY_ARMOR, lv43.transform(WolfEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.ZOGLIN, lv25);
        builder.put(EntityModelLayers.ZOGLIN_BABY, lv26);
        builder.put(EntityModelLayers.ZOMBIE, lv);
        builder.put(EntityModelLayers.ZOMBIE_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.ZOMBIE_OUTER_ARMOR, lv2);
        builder.put(EntityModelLayers.ZOMBIE_BABY, lv.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.ZOMBIE_BABY_INNER_ARMOR, lv4.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.ZOMBIE_BABY_OUTER_ARMOR, lv2.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.ZOMBIE_HEAD, lv21);
        builder.put(EntityModelLayers.ZOMBIE_HORSE, lv7);
        builder.put(EntityModelLayers.ZOMBIE_HORSE_BABY, lv8);
        builder.put(EntityModelLayers.ZOMBIE_VILLAGER, lv44);
        builder.put(EntityModelLayers.ZOMBIE_VILLAGER_INNER_ARMOR, ZombieVillagerEntityModel.getArmorTexturedModelData(HAT_DILATION));
        builder.put(EntityModelLayers.ZOMBIE_VILLAGER_OUTER_ARMOR, ZombieVillagerEntityModel.getArmorTexturedModelData(ARMOR_DILATION));
        builder.put(EntityModelLayers.ZOMBIE_VILLAGER_BABY, lv44.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.ZOMBIE_VILLAGER_BABY_INNER_ARMOR, ZombieVillagerEntityModel.getArmorTexturedModelData(HAT_DILATION).transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.ZOMBIE_VILLAGER_BABY_OUTER_ARMOR, ZombieVillagerEntityModel.getArmorTexturedModelData(ARMOR_DILATION).transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.ZOMBIFIED_PIGLIN, lv19);
        builder.put(EntityModelLayers.ZOMBIFIED_PIGLIN_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.ZOMBIFIED_PIGLIN_OUTER_ARMOR, lv3);
        builder.put(EntityModelLayers.ZOMBIFIED_PIGLIN_BABY, lv19.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.ZOMBIFIED_PIGLIN_BABY_INNER_ARMOR, lv4.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.ZOMBIFIED_PIGLIN_BABY_OUTER_ARMOR, lv3.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put(EntityModelLayers.BAMBOO_BOAT, RaftEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.BAMBOO_CHEST_BOAT, RaftEntityModel.getChestTexturedModelData());
        TexturedModelData lv57 = BoatEntityModel.getTexturedModelData();
        TexturedModelData lv58 = BoatEntityModel.getChestTexturedModelData();
        builder.put(EntityModelLayers.OAK_BOAT, lv57);
        builder.put(EntityModelLayers.OAK_CHEST_BOAT, lv58);
        builder.put(EntityModelLayers.SPRUCE_BOAT, lv57);
        builder.put(EntityModelLayers.SPRUCE_CHEST_BOAT, lv58);
        builder.put(EntityModelLayers.BIRCH_BOAT, lv57);
        builder.put(EntityModelLayers.BIRCH_CHEST_BOAT, lv58);
        builder.put(EntityModelLayers.JUNGLE_BOAT, lv57);
        builder.put(EntityModelLayers.JUNGLE_CHEST_BOAT, lv58);
        builder.put(EntityModelLayers.ACACIA_BOAT, lv57);
        builder.put(EntityModelLayers.ACACIA_CHEST_BOAT, lv58);
        builder.put(EntityModelLayers.CHERRY_BOAT, lv57);
        builder.put(EntityModelLayers.CHERRY_CHEST_BOAT, lv58);
        builder.put(EntityModelLayers.DARK_OAK_BOAT, lv57);
        builder.put(EntityModelLayers.DARK_OAK_CHEST_BOAT, lv58);
        builder.put(EntityModelLayers.PALE_OAK_BOAT, lv57);
        builder.put(EntityModelLayers.PALE_OAK_CHEST_BOAT, lv58);
        builder.put(EntityModelLayers.MANGROVE_BOAT, lv57);
        builder.put(EntityModelLayers.MANGROVE_CHEST_BOAT, lv58);
        TexturedModelData lv59 = SignBlockEntityRenderer.getTexturedModelData(true);
        TexturedModelData lv60 = SignBlockEntityRenderer.getTexturedModelData(false);
        WoodType.stream().forEach(woodType -> {
            builder.put(EntityModelLayers.createStandingSign(woodType), lv59);
            builder.put(EntityModelLayers.createWallSign(woodType), lv60);
            for (HangingSignBlockEntityRenderer.AttachmentType lv : HangingSignBlockEntityRenderer.AttachmentType.values()) {
                TexturedModelData lv2 = HangingSignBlockEntityRenderer.getTexturedModelData(lv);
                builder.put(EntityModelLayers.createHangingSign(woodType, lv), lv2);
            }
        });
        ImmutableMap<EntityModelLayer, TexturedModelData> immutableMap = builder.build();
        List list = EntityModelLayers.getLayers().filter(layer -> !immutableMap.containsKey(layer)).collect(Collectors.toList());
        if (!list.isEmpty()) {
            throw new IllegalStateException("Missing layer definitions: " + String.valueOf(list));
        }
        return immutableMap;
    }
}

